import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import {
  Search,
  SlidersHorizontal,
  BrainCircuit,
  AlertTriangle,
  ShieldCheck,
  Activity,
  Clock3,
  TrendingDown,
  TrendingUp,
  Eye,
  ChevronRight,
  X,
  Sparkles,
  CheckCircle2,
  CircleAlert,
} from "lucide-react";

// =========================================================
// AI MONITOR DATA
// =========================================================
// Temporary frontend-only development data.
//
// IMPORTANT:
// These AI insights are MOCK DATA.
// In production, risk scores, anomaly detection,
// recommendations, and alerts must be generated by
// authenticated backend/AI services.
//
// Never trust AI results or project information supplied
// directly by the frontend.
// =========================================================

const aiProjectRecords = [
  {
    id: 1,
    project: "Ward 5 Road Improvement",
    location: "Lalitpur",
    contractor: "Himalayan Construction Pvt. Ltd.",
    progress: 72,
    plannedProgress: 78,
    budgetUtilization: 68,
    riskScore: 28,
    riskLevel: "Low",
    anomaly: "No significant anomaly detected",
    recommendation:
      "Project is progressing close to schedule. Continue routine monitoring.",
    lastAnalysis: "2026-08-23 10:30",
  },
  {
    id: 2,
    project: "Dhobighat Drainage Project",
    location: "Lalitpur",
    contractor: "Everest Infrastructure Pvt. Ltd.",
    progress: 48,
    plannedProgress: 65,
    budgetUtilization: 61,
    riskScore: 64,
    riskLevel: "Medium",
    anomaly: "Progress is below planned schedule",
    recommendation:
      "Review construction schedule and contractor resource allocation.",
    lastAnalysis: "2026-08-23 10:18",
  },
  {
    id: 3,
    project: "Community Building Construction",
    location: "Kathmandu",
    contractor: "Kathmandu Builders Pvt. Ltd.",
    progress: 31,
    plannedProgress: 58,
    budgetUtilization: 76,
    riskScore: 87,
    riskLevel: "High",
    anomaly: "Significant schedule and expenditure deviation",
    recommendation:
      "Immediate project review recommended. Verify physical progress and financial utilization.",
    lastAnalysis: "2026-08-23 09:52",
  },
  {
    id: 4,
    project: "Ward 7 Drinking Water Pipeline",
    location: "Bhaktapur",
    contractor: "Green Valley Engineering",
    progress: 100,
    plannedProgress: 100,
    budgetUtilization: 94,
    riskScore: 8,
    riskLevel: "Low",
    anomaly: "No significant anomaly detected",
    recommendation:
      "Project appears complete. Proceed with final verification and documentation.",
    lastAnalysis: "2026-08-23 09:40",
  },
  {
    id: 5,
    project: "Municipal Health Post Construction",
    location: "Kathmandu",
    contractor: "Sagarmatha Builders",
    progress: 56,
    plannedProgress: 71,
    budgetUtilization: 82,
    riskScore: 73,
    riskLevel: "High",
    anomaly: "High budget utilization relative to physical progress",
    recommendation:
      "Perform financial and physical progress verification before further payment.",
    lastAnalysis: "2026-08-23 09:25",
  },
  {
    id: 6,
    project: "Ward 2 Street Lighting Project",
    location: "Lalitpur",
    contractor: "Bright Nepal Engineering",
    progress: 84,
    plannedProgress: 81,
    budgetUtilization: 79,
    riskScore: 18,
    riskLevel: "Low",
    anomaly: "Progress is slightly ahead of schedule",
    recommendation:
      "Continue normal monitoring. Current progress appears healthy.",
    lastAnalysis: "2026-08-23 09:10",
  },
];

// =========================================================
// AI ALERTS
// =========================================================

const aiAlerts = [
  {
    id: 1,
    severity: "High",
    title: "Schedule deviation detected",
    project: "Community Building Construction",
    message:
      "Physical progress is significantly below the expected project schedule.",
    time: "18 minutes ago",
  },
  {
    id: 2,
    severity: "High",
    title: "Budget-progress mismatch",
    project: "Municipal Health Post Construction",
    message:
      "Budget utilization is high compared with reported physical progress.",
    time: "45 minutes ago",
  },
  {
    id: 3,
    severity: "Medium",
    title: "Progress delay detected",
    project: "Dhobighat Drainage Project",
    message:
      "Current progress is below the planned project milestone.",
    time: "1 hour ago",
  },
];

// =========================================================
// RISK STYLES
// =========================================================

const riskStyles = {
  Low: {
    badge: "border-emerald-200 bg-emerald-50 text-emerald-700",
    icon: CheckCircle2,
    iconColor: "text-emerald-600",
  },

  Medium: {
    badge: "border-amber-200 bg-amber-50 text-amber-700",
    icon: CircleAlert,
    iconColor: "text-amber-600",
  },

  High: {
    badge: "border-red-200 bg-red-50 text-red-700",
    icon: AlertTriangle,
    iconColor: "text-red-600",
  },
};

// =========================================================
// AI MONITOR PAGE
// =========================================================

export default function AIMonitor() {
  const [searchTerm, setSearchTerm] = useState("");
  const [riskFilter, setRiskFilter] = useState("All");
  const [selectedProject, setSelectedProject] = useState(null);

  // =======================================================
  // FILTER PROJECTS
  // =======================================================

  const filteredProjects = useMemo(() => {
    const search = searchTerm.toLowerCase().trim();

    return aiProjectRecords.filter((project) => {
      const matchesSearch =
        project.project.toLowerCase().includes(search) ||
        project.location.toLowerCase().includes(search) ||
        project.contractor.toLowerCase().includes(search) ||
        project.anomaly.toLowerCase().includes(search);

      const matchesRisk =
        riskFilter === "All" ||
        project.riskLevel === riskFilter;

      return matchesSearch && matchesRisk;
    });
  }, [searchTerm, riskFilter]);

  // =======================================================
  // CLEAR FILTERS
  // =======================================================

  const clearFilters = () => {
    setSearchTerm("");
    setRiskFilter("All");
  };

  const hasActiveFilters =
    searchTerm || riskFilter !== "All";

  // =======================================================
  // CALCULATED RISK COUNTS
  // =======================================================

  const highRiskCount = aiProjectRecords.filter(
    (project) => project.riskLevel === "High"
  ).length;

  const mediumRiskCount = aiProjectRecords.filter(
    (project) => project.riskLevel === "Medium"
  ).length;

  const lowRiskCount = aiProjectRecords.filter(
    (project) => project.riskLevel === "Low"
  ).length;

  // =======================================================
  // MAIN PAGE
  // =======================================================

  return (
    <main className="w-full">
      <div className="mx-auto w-full max-w-[1800px] p-4 sm:p-5 md:p-6 lg:p-8">

        {/* =================================================
            PAGE HEADER
        ================================================= */}

        <section className="mb-6">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">

            <div>
              <p className="text-xs font-medium uppercase tracking-wider text-blue-600 sm:text-sm">
                Intelligent Infrastructure Monitoring
              </p>

              <h1 className="mt-1 flex items-center gap-2 text-xl font-bold text-slate-900 sm:text-2xl lg:text-3xl">
                AI Monitor
                <Sparkles
                  size={20}
                  className="text-blue-600"
                />
              </h1>

              <p className="mt-2 max-w-2xl text-xs leading-5 text-slate-500 sm:text-sm sm:leading-6">
                Analyze project progress, identify potential risks,
                detect anomalies, and prioritize infrastructure
                projects that require administrative attention.
              </p>
            </div>

            {/* AI Status */}

            <div className="flex w-fit items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2">
              <span className="relative flex h-2.5 w-2.5">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75" />
                <span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-emerald-500" />
              </span>

              <span className="text-xs font-semibold text-emerald-700">
                AI Monitoring Active
              </span>
            </div>

          </div>
        </section>

        {/* =================================================
            AI OVERVIEW
        ================================================= */}

        <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4 sm:gap-4">

          {/* Overall */}

          <article className="rounded-xl border border-blue-200 bg-white p-4 shadow-sm sm:p-5">
            <div className="flex items-start justify-between gap-3">

              <div>
                <p className="text-xs font-medium text-slate-500 sm:text-sm">
                  AI Risk Score
                </p>

                <p className="mt-2 text-2xl font-bold text-slate-900 sm:text-3xl">
                  61
                  <span className="text-sm font-medium text-slate-400">
                    /100
                  </span>
                </p>

                <p className="mt-2 flex items-center gap-1 text-[11px] text-amber-600 sm:text-xs">
                  <TrendingUp size={13} />
                  Requires attention
                </p>
              </div>

              <div className="rounded-lg bg-blue-50 p-2.5 text-blue-600">
                <BrainCircuit size={21} />
              </div>

            </div>
          </article>

          {/* High Risk */}

          <article className="rounded-xl border border-red-200 bg-white p-4 shadow-sm sm:p-5">
            <div className="flex items-start justify-between gap-3">

              <div>
                <p className="text-xs font-medium text-slate-500 sm:text-sm">
                  High Risk
                </p>

                <p className="mt-2 text-2xl font-bold text-slate-900 sm:text-3xl">
                  {highRiskCount}
                </p>

                <p className="mt-2 text-[11px] text-red-600 sm:text-xs">
                  Immediate review recommended
                </p>
              </div>

              <div className="rounded-lg bg-red-50 p-2.5 text-red-600">
                <AlertTriangle size={21} />
              </div>

            </div>
          </article>

          {/* Medium Risk */}

          <article className="rounded-xl border border-amber-200 bg-white p-4 shadow-sm sm:p-5">
            <div className="flex items-start justify-between gap-3">

              <div>
                <p className="text-xs font-medium text-slate-500 sm:text-sm">
                  Medium Risk
                </p>

                <p className="mt-2 text-2xl font-bold text-slate-900 sm:text-3xl">
                  {mediumRiskCount}
                </p>

                <p className="mt-2 text-[11px] text-amber-600 sm:text-xs">
                  Requires closer monitoring
                </p>
              </div>

              <div className="rounded-lg bg-amber-50 p-2.5 text-amber-600">
                <Activity size={21} />
              </div>

            </div>
          </article>

          {/* Low Risk */}

          <article className="rounded-xl border border-emerald-200 bg-white p-4 shadow-sm sm:p-5">
            <div className="flex items-start justify-between gap-3">

              <div>
                <p className="text-xs font-medium text-slate-500 sm:text-sm">
                  Low Risk
                </p>

                <p className="mt-2 text-2xl font-bold text-slate-900 sm:text-3xl">
                  {lowRiskCount}
                </p>

                <p className="mt-2 text-[11px] text-emerald-600 sm:text-xs">
                  Normal monitoring
                </p>
              </div>

              <div className="rounded-lg bg-emerald-50 p-2.5 text-emerald-600">
                <ShieldCheck size={21} />
              </div>

            </div>
          </article>

        </section>

        {/* =================================================
            AI ALERTS
        ================================================= */}

        <section className="mt-6 rounded-xl border border-slate-200 bg-white shadow-sm sm:mt-8">

          <div className="border-b border-slate-200 px-4 py-4 sm:px-5">
            <div className="flex items-center gap-2">

              <div className="rounded-lg bg-red-50 p-2 text-red-600">
                <AlertTriangle size={17} />
              </div>

              <div>
                <h2 className="text-sm font-semibold text-slate-900 sm:text-base">
                  AI-Detected Alerts
                </h2>

                <p className="mt-1 text-xs text-slate-500">
                  Potential issues identified from project monitoring data.
                </p>
              </div>

            </div>
          </div>

          <div className="divide-y divide-slate-100">

            {aiAlerts.map((alert) => (

              <div
                key={alert.id}
                className="flex flex-col gap-3 px-4 py-4 sm:flex-row sm:items-start sm:justify-between sm:px-5"
              >

                <div className="flex items-start gap-3">

                  <div
                    className={`mt-0.5 rounded-full p-2 ${
                      alert.severity === "High"
                        ? "bg-red-50 text-red-600"
                        : "bg-amber-50 text-amber-600"
                    }`}
                  >
                    <CircleAlert size={16} />
                  </div>

                  <div>

                    <div className="flex flex-wrap items-center gap-2">

                      <p className="text-sm font-semibold text-slate-800">
                        {alert.title}
                      </p>

                      <span
                        className={`rounded-full border px-2 py-0.5 text-[10px] font-medium ${
                          alert.severity === "High"
                            ? "border-red-200 bg-red-50 text-red-700"
                            : "border-amber-200 bg-amber-50 text-amber-700"
                        }`}
                      >
                        {alert.severity}
                      </span>

                    </div>

                    <p className="mt-1 text-xs font-medium text-slate-600">
                      {alert.project}
                    </p>

                    <p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">
                      {alert.message}
                    </p>

                  </div>

                </div>

                <span className="shrink-0 text-[11px] text-slate-400">
                  {alert.time}
                </span>

              </div>

            ))}

          </div>

        </section>

        {/* =================================================
            SEARCH & FILTERS
        ================================================= */}

        <section className="mt-6 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:mt-8 sm:p-5">

          <div className="flex items-center gap-2">

            <SlidersHorizontal
              size={17}
              className="text-slate-500"
            />

            <h2 className="text-sm font-semibold text-slate-800">
              AI Risk Search & Filters
            </h2>

          </div>

          <div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2">

            {/* Search */}

            <div className="relative">

              <Search
                size={17}
                className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"
              />

              <input
                type="text"
                value={searchTerm}
                onChange={(event) =>
                  setSearchTerm(event.target.value)
                }
                placeholder="Search projects, contractors, anomalies..."
                className="h-10 w-full rounded-lg border border-slate-200 bg-white pl-9 pr-3 text-sm text-slate-700 outline-none transition placeholder:text-slate-400 focus:border-blue-500 focus:ring-2 focus:ring-blue-100"
              />

            </div>

            {/* Risk */}

            <select
              value={riskFilter}
              onChange={(event) =>
                setRiskFilter(event.target.value)
              }
              className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-600 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100"
            >

              <option value="All">
                All Risk Levels
              </option>

              <option value="High">
                High Risk
              </option>

              <option value="Medium">
                Medium Risk
              </option>

              <option value="Low">
                Low Risk
              </option>

            </select>

          </div>

          {hasActiveFilters && (

            <div className="mt-4 flex flex-wrap items-center gap-2">

              <span className="text-xs text-slate-500">
                Filters applied
              </span>

              <button
                type="button"
                onClick={clearFilters}
                className="flex items-center gap-1 rounded-md px-2 py-1 text-xs font-medium text-blue-600 transition hover:bg-blue-50"
              >
                Clear all
                <X size={13} />
              </button>

            </div>

          )}

        </section>

        {/* =================================================
            AI PROJECT ANALYSIS
        ================================================= */}

        <section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm sm:mt-8">

          <div className="border-b border-slate-200 px-4 py-4 sm:px-6">

            <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">

              <div>
                <h2 className="text-sm font-semibold text-slate-900 sm:text-base">
                  AI Project Risk Analysis
                </h2>

                <p className="mt-1 text-xs text-slate-500">
                  AI-generated risk indicators for monitored infrastructure projects.
                </p>
              </div>

              <div className="text-xs text-slate-400">
                {filteredProjects.length} project
                {filteredProjects.length !== 1 ? "s" : ""}
              </div>

            </div>

          </div>

          {/* Desktop */}

          <div className="hidden overflow-x-auto lg:block">

            <table className="w-full min-w-[1200px] text-left text-sm">

              <thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500">

                <tr>

                  <th className="px-6 py-4 font-semibold">
                    Project
                  </th>

                  <th className="px-6 py-4 font-semibold">
                    Progress
                  </th>

                  <th className="px-6 py-4 font-semibold">
                    Budget Used
                  </th>

                  <th className="px-6 py-4 font-semibold">
                    Risk Score
                  </th>

                  <th className="px-6 py-4 font-semibold">
                    AI Finding
                  </th>

                  <th className="px-6 py-4 font-semibold">
                    Risk
                  </th>

                  <th className="px-6 py-4 text-right font-semibold">
                    Action
                  </th>

                </tr>

              </thead>

              <tbody className="divide-y divide-slate-100">

                {filteredProjects.length > 0 ? (

                  filteredProjects.map((project) => {

                    const config =
                      riskStyles[project.riskLevel];

                    const RiskIcon = config.icon;

                    const progressDifference =
                      project.progress -
                      project.plannedProgress;

                    return (

                      <tr
                        key={project.id}
                        className="transition hover:bg-slate-50"
                      >

                        {/* Project */}

                        <td className="px-6 py-5">

                          <p className="font-semibold text-slate-900">
                            {project.project}
                          </p>

                          <p className="mt-1 text-xs text-slate-500">
                            {project.location}
                          </p>

                          <p className="mt-1 text-[11px] text-slate-400">
                            {project.contractor}
                          </p>

                        </td>

                        {/* Progress */}

                        <td className="px-6 py-5">

                          <div className="w-40">

                            <div className="flex items-center justify-between">

                              <span className="text-xs font-semibold text-slate-700">
                                {project.progress}%
                              </span>

                              <span
                                className={`flex items-center gap-1 text-[10px] ${
                                  progressDifference < 0
                                    ? "text-red-600"
                                    : "text-emerald-600"
                                }`}
                              >
                                {progressDifference < 0 ? (
                                  <TrendingDown size={12} />
                                ) : (
                                  <TrendingUp size={12} />
                                )}

                                Planned {project.plannedProgress}%
                              </span>

                            </div>

                            <div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-slate-100">

                              <div
                                className="h-full rounded-full bg-blue-600"
                                style={{
                                  width: `${project.progress}%`,
                                }}
                              />

                            </div>

                          </div>

                        </td>

                        {/* Budget */}

                        <td className="px-6 py-5">

                          <span
                            className={`text-xs font-semibold ${
                              project.budgetUtilization >= 80
                                ? "text-red-600"
                                : project.budgetUtilization >= 60
                                ? "text-amber-600"
                                : "text-slate-700"
                            }`}
                          >
                            {project.budgetUtilization}%
                          </span>

                          <p className="mt-1 text-[10px] text-slate-400">
                            utilization
                          </p>

                        </td>

                        {/* Risk Score */}

                        <td className="px-6 py-5">

                          <div className="flex items-center gap-2">

                            <div className="h-2 w-20 overflow-hidden rounded-full bg-slate-100">

                              <div
                                className={`h-full rounded-full ${
                                  project.riskScore >= 75
                                    ? "bg-red-500"
                                    : project.riskScore >= 50
                                    ? "bg-amber-500"
                                    : "bg-emerald-500"
                                }`}
                                style={{
                                  width: `${project.riskScore}%`,
                                }}
                              />

                            </div>

                            <span className="text-xs font-bold text-slate-700">
                              {project.riskScore}
                            </span>

                          </div>

                        </td>

                        {/* Finding */}

                        <td className="max-w-xs px-6 py-5">

                          <p className="text-xs leading-5 text-slate-600">
                            {project.anomaly}
                          </p>

                        </td>

                        {/* Risk */}

                        <td className="px-6 py-5">

                          <span
                            className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium ${config.badge}`}
                          >

                            <RiskIcon size={13} />

                            {project.riskLevel}

                          </span>

                        </td>

                        {/* Action */}

                        <td className="px-6 py-5 text-right">

                          <button
                            type="button"
                            onClick={() =>
                              setSelectedProject(project)
                            }
                            className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium text-slate-600 transition hover:border-blue-200 hover:bg-blue-50 hover:text-blue-600"
                          >
                            <Eye size={14} />
                            Analyze
                          </button>

                        </td>

                      </tr>

                    );
                  })

                ) : (

                  <tr>

                    <td
                      colSpan="7"
                      className="px-6 py-12 text-center"
                    >

                      <BrainCircuit
                        size={25}
                        className="mx-auto text-slate-400"
                      />

                      <p className="mt-3 text-sm font-medium text-slate-700">
                        No projects found
                      </p>

                      <p className="mt-1 text-xs text-slate-500">
                        Try changing your search or risk filter.
                      </p>

                    </td>

                  </tr>

                )}

              </tbody>

            </table>

          </div>

          {/* Mobile / Tablet */}

          <div className="divide-y divide-slate-100 lg:hidden">

            {filteredProjects.length > 0 ? (

              filteredProjects.map((project) => {

                const config =
                  riskStyles[project.riskLevel];

                const RiskIcon = config.icon;

                return (

                  <article
                    key={project.id}
                    className="p-4 sm:p-5"
                  >

                    <div className="flex items-start justify-between gap-3">

                      <div className="min-w-0">

                        <h3 className="text-sm font-semibold text-slate-900">
                          {project.project}
                        </h3>

                        <p className="mt-1 text-xs text-slate-500">
                          {project.location}
                        </p>

                      </div>

                      <span
                        className={`inline-flex shrink-0 items-center gap-1 rounded-full border px-2 py-1 text-[10px] font-medium ${config.badge}`}
                      >
                        <RiskIcon size={12} />
                        {project.riskLevel}
                      </span>

                    </div>

                    <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">

                      <div className="rounded-lg bg-slate-50 p-3">

                        <p className="text-[10px] uppercase tracking-wide text-slate-400">
                          Progress
                        </p>

                        <p className="mt-1 text-sm font-bold text-slate-800">
                          {project.progress}%
                        </p>

                      </div>

                      <div className="rounded-lg bg-slate-50 p-3">

                        <p className="text-[10px] uppercase tracking-wide text-slate-400">
                          Planned
                        </p>

                        <p className="mt-1 text-sm font-bold text-slate-800">
                          {project.plannedProgress}%
                        </p>

                      </div>

                      <div className="rounded-lg bg-slate-50 p-3">

                        <p className="text-[10px] uppercase tracking-wide text-slate-400">
                          Budget
                        </p>

                        <p className="mt-1 text-sm font-bold text-slate-800">
                          {project.budgetUtilization}%
                        </p>

                      </div>

                      <div className="rounded-lg bg-slate-50 p-3">

                        <p className="text-[10px] uppercase tracking-wide text-slate-400">
                          Risk Score
                        </p>

                        <p className="mt-1 text-sm font-bold text-slate-800">
                          {project.riskScore}/100
                        </p>

                      </div>

                    </div>

                    <div className="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-3">

                      <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">
                        AI Finding
                      </p>

                      <p className="mt-1 text-xs leading-5 text-slate-600">
                        {project.anomaly}
                      </p>

                    </div>

                    <button
                      type="button"
                      onClick={() =>
                        setSelectedProject(project)
                      }
                      className="mt-4 inline-flex w-full items-center justify-center gap-1 rounded-lg border border-slate-200 px-3 py-2.5 text-xs font-medium text-slate-600 transition hover:border-blue-200 hover:bg-blue-50 hover:text-blue-600"
                    >
                      <Eye size={14} />
                      View AI Analysis
                    </button>

                  </article>

                );

              })

            ) : (

              <div className="px-4 py-12 text-center">

                <BrainCircuit
                  size={25}
                  className="mx-auto text-slate-400"
                />

                <p className="mt-3 text-sm font-medium text-slate-700">
                  No projects found
                </p>

                <p className="mt-1 text-xs text-slate-500">
                  Try changing your search or risk filter.
                </p>

              </div>

            )}

          </div>

        </section>

        {/* =================================================
            AI RECOMMENDATION
        ================================================= */}

        <section className="mt-6 rounded-xl border border-blue-100 bg-blue-50 p-4 sm:mt-8 sm:p-5">

          <div className="flex items-start gap-3">

            <div className="rounded-lg bg-white p-2 text-blue-600 shadow-sm">
              <BrainCircuit size={18} />
            </div>

            <div>

              <p className="text-xs font-semibold text-blue-900 sm:text-sm">
                AI Monitoring Recommendation
              </p>

              <p className="mt-1 max-w-4xl text-xs leading-5 text-blue-700">
                Based on the current development dataset, projects
                with significant differences between physical progress
                and planned progress should receive priority for
                administrative review. Financial utilization should
                also be compared with verified physical work before
                approving further project payments.
              </p>

            </div>

          </div>

        </section>

        {/* =================================================
            SECURITY / AI DATA NOTE
        ================================================= */}

        <section className="mt-6 flex items-start gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:mt-8">

          <ShieldCheck
            size={18}
            className="mt-0.5 shrink-0 text-slate-600"
          />

          <div>

            <p className="text-xs font-semibold text-slate-800 sm:text-sm">
              Secure AI Monitoring
            </p>

            <p className="mt-1 text-xs leading-5 text-slate-600">
              AI findings shown here are currently mock development
              results. In production, project data must be retrieved
              through authenticated APIs, while AI analysis should run
              on trusted backend services. Sensitive project,
              financial, contractor, and verification information must
              be protected using role-based authorization, input
              validation, audit logging, and secure data handling.
            </p>

          </div>

        </section>

        {/* =================================================
            AI ANALYSIS MODAL
        ================================================= */}

        {selectedProject && (

          <div
            className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4 backdrop-blur-sm"
            onClick={() => setSelectedProject(null)}
          >

            <div
              className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl border border-slate-200 bg-white shadow-2xl"
              onClick={(event) =>
                event.stopPropagation()
              }
            >

              {/* Modal Header */}

              <div className="flex items-start justify-between gap-4 border-b border-slate-200 p-5 sm:p-6">

                <div className="flex items-start gap-3">

                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-blue-50 text-blue-600">
                    <BrainCircuit size={20} />
                  </div>

                  <div>

                    <p className="text-xs font-medium uppercase tracking-wide text-blue-600">
                      AI Project Analysis
                    </p>

                    <h2 className="mt-1 text-base font-bold text-slate-900 sm:text-lg">
                      {selectedProject.project}
                    </h2>

                    <p className="mt-1 text-xs text-slate-500">
                      {selectedProject.location}
                    </p>

                  </div>

                </div>

                <button
                  type="button"
                  onClick={() =>
                    setSelectedProject(null)
                  }
                  className="rounded-lg p-2 text-slate-400 transition hover:bg-slate-100 hover:text-slate-600"
                  aria-label="Close AI analysis"
                >
                  <X size={18} />
                </button>

              </div>

              {/* Modal Content */}

              <div className="p-5 sm:p-6">

                {/* Risk Score */}

                <div className="rounded-xl border border-slate-200 bg-slate-50 p-4">

                  <div className="flex items-center justify-between gap-3">

                    <div>

                      <p className="text-xs font-medium text-slate-500">
                        AI Risk Score
                      </p>

                      <p className="mt-1 text-3xl font-bold text-slate-900">
                        {selectedProject.riskScore}
                        <span className="text-sm font-medium text-slate-400">
                          /100
                        </span>
                      </p>

                    </div>

                    <span
                      className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${
                        riskStyles[selectedProject.riskLevel].badge
                      }`}
                    >
                      {selectedProject.riskLevel} Risk
                    </span>

                  </div>

                  <div className="mt-4 h-2 overflow-hidden rounded-full bg-white">

                    <div
                      className={`h-full rounded-full ${
                        selectedProject.riskScore >= 75
                          ? "bg-red-500"
                          : selectedProject.riskScore >= 50
                          ? "bg-amber-500"
                          : "bg-emerald-500"
                      }`}
                      style={{
                        width: `${selectedProject.riskScore}%`,
                      }}
                    />

                  </div>

                </div>

                {/* Metrics */}

                <div className="mt-4 grid grid-cols-2 gap-3">

                  <div className="rounded-lg border border-slate-200 p-4">

                    <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">
                      Physical Progress
                    </p>

                    <p className="mt-1 text-lg font-bold text-slate-800">
                      {selectedProject.progress}%
                    </p>

                  </div>

                  <div className="rounded-lg border border-slate-200 p-4">

                    <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">
                      Planned Progress
                    </p>

                    <p className="mt-1 text-lg font-bold text-slate-800">
                      {selectedProject.plannedProgress}%
                    </p>

                  </div>

                  <div className="rounded-lg border border-slate-200 p-4">

                    <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">
                      Budget Utilization
                    </p>

                    <p className="mt-1 text-lg font-bold text-slate-800">
                      {selectedProject.budgetUtilization}%
                    </p>

                  </div>

                  <div className="rounded-lg border border-slate-200 p-4">

                    <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">
                      Last Analysis
                    </p>

                    <p className="mt-1 text-xs font-semibold text-slate-800">
                      {selectedProject.lastAnalysis}
                    </p>

                  </div>

                </div>

                {/* Finding */}

                <div className="mt-4 rounded-xl border border-amber-100 bg-amber-50 p-4">

                  <div className="flex items-start gap-2">

                    <AlertTriangle
                      size={17}
                      className="mt-0.5 shrink-0 text-amber-600"
                    />

                    <div>

                      <p className="text-xs font-semibold text-amber-900">
                        Detected Finding
                      </p>

                      <p className="mt-1 text-xs leading-5 text-amber-800">
                        {selectedProject.anomaly}
                      </p>

                    </div>

                  </div>

                </div>

                {/* Recommendation */}

                <div className="mt-4 rounded-xl border border-blue-100 bg-blue-50 p-4">

                  <div className="flex items-start gap-2">

                    <Sparkles
                      size={17}
                      className="mt-0.5 shrink-0 text-blue-600"
                    />

                    <div>

                      <p className="text-xs font-semibold text-blue-900">
                        AI Recommendation
                      </p>

                      <p className="mt-1 text-xs leading-5 text-blue-800">
                        {selectedProject.recommendation}
                      </p>

                    </div>

                  </div>

                </div>

              </div>

              {/* Modal Footer */}

              <div className="flex flex-col gap-2 border-t border-slate-200 p-5 sm:flex-row sm:justify-end sm:p-6">

                <button
                  type="button"
                  onClick={() =>
                    setSelectedProject(null)
                  }
                  className="rounded-lg border border-slate-200 px-4 py-2.5 text-xs font-semibold text-slate-600 transition hover:bg-slate-50"
                >
                  Close
                </button>

                <Link
                  to={`/projects/${selectedProject.id}`}
                  onClick={() =>
                    setSelectedProject(null)
                  }
                  className="inline-flex items-center justify-center gap-1 rounded-lg bg-blue-600 px-4 py-2.5 text-xs font-semibold text-white transition hover:bg-blue-700"
                >
                  View Project
                  <ChevronRight size={14} />
                </Link>

              </div>

            </div>

          </div>

        )}

      </div>
    </main>
  );
} 